'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'

export default function TimetableClient({ regulations, batches, semesters, initialSemester, slots, workingDays, timeSlots }: any) {
  const router = useRouter()
  const [selectedReg, setSelectedReg] = useState('')
  const [selectedBatch, setSelectedBatch] = useState('')
  const [selectedSemester, setSelectedSemester] = useState(initialSemester || '')

  const filteredBatches = batches.filter((b: any) => b.regulation_id === selectedReg)
  const filteredSemesters = semesters.filter((s: any) => s.batch_id === selectedBatch)

  const handleSemesterSelect = (val: string) => {
    setSelectedSemester(val)
    router.push(`/timetable?semester=${val}`)
  }

  // Create a 2D lookup grid for easy rendering: grid[day_of_week][period_number]
  const grid: Record<number, Record<number, any>> = {}
  
  // Safe fallback if the data is not yet available
  const days = workingDays || []
  const periods = timeSlots || []

  days.forEach((d: any) => {
    grid[d.day_of_week] = {}
    periods.forEach((p: any) => {
      grid[d.day_of_week][p.period_number] = null
    })
  })

  slots?.forEach((slot: any) => {
    if(grid[slot.day_of_week]) {
       grid[slot.day_of_week][slot.period_number] = slot
    }
  })

  const selectedRegName = regulations.find((r: any) => r.id === selectedReg)?.name || ''
  const selectedBatchName = batches.find((b: any) => b.id === selectedBatch)?.name || ''
  const selectedSemesterName = semesters.find((s: any) => s.id === selectedSemester)?.name || ''

  return (
    <div className="max-w-[1400px] mx-auto py-10 px-6 print:p-0 print:m-0 print:max-w-full">
      <div className="mb-8 print:hidden">
        <h1 className="text-3xl font-bold text-slate-900">Generated Timetable</h1>
        <p className="text-slate-600 mt-1">View the conflict-free schedule generated by the engine.</p>
      </div>

      <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 mb-8 print:hidden">
        <h2 className="text-xl font-bold text-slate-900 mb-6">Select Configuration</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="flex flex-col space-y-2">
            <Label className="text-slate-700 font-semibold">Regulation</Label>
            <select 
              className="flex h-10 w-full rounded-lg border border-slate-200 bg-slate-50/50 px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 shadow-sm"
              value={selectedReg} 
              onChange={(e) => { setSelectedReg(e.target.value); setSelectedBatch(''); setSelectedSemester(''); }}
            >
              <option value="" disabled>Select Regulation</option>
              {regulations.map((r: any) => <option key={r.id} value={r.id}>{r.name}</option>)}
            </select>
          </div>

          <div className="flex flex-col space-y-2">
            <Label className="text-slate-700 font-semibold">Batch</Label>
            <select 
              className="flex h-10 w-full rounded-lg border border-slate-200 bg-slate-50/50 px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 shadow-sm disabled:cursor-not-allowed disabled:opacity-50"
              disabled={!selectedReg} 
              value={selectedBatch} 
              onChange={(e) => { setSelectedBatch(e.target.value); setSelectedSemester(''); }}
            >
              <option value="" disabled>Select Batch</option>
              {filteredBatches.map((b: any) => <option key={b.id} value={b.id}>{b.name}</option>)}
            </select>
          </div>

          <div className="flex flex-col space-y-2">
            <Label className="text-slate-700 font-semibold">Semester</Label>
            <select 
              className="flex h-10 w-full rounded-lg border border-slate-200 bg-slate-50/50 px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 shadow-sm disabled:cursor-not-allowed disabled:opacity-50"
              disabled={!selectedBatch} 
              value={selectedSemester} 
              onChange={(e) => handleSemesterSelect(e.target.value)}
            >
              <option value="" disabled>Select Semester</option>
              {filteredSemesters.map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
        </div>
      </div>

      {selectedSemester && (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500 print:shadow-none print:border-none print:m-0 print:p-0">
          <div className="p-6 border-b border-slate-200 bg-slate-50 flex justify-between items-center print:hidden">
            <h2 className="text-xl font-bold text-slate-900">
              Weekly Schedule
            </h2>
            <div className="flex gap-4">
              <Button variant="default" className="bg-blue-600 hover:bg-blue-700 text-white font-medium shadow-sm transition-all rounded-lg" onClick={() => window.print()}>
                Download PDF
              </Button>
              <Button variant="outline" className="border-slate-200 shadow-sm" onClick={() => window.print()}>
                Print Timetable
              </Button>
            </div>
          </div>
          
          <div className="hidden print:block mb-6 text-center">
            <h1 className="text-2xl font-bold text-slate-900">Class Timetable</h1>
            <p className="text-slate-600 mt-1">
              {selectedRegName} | {selectedBatchName} | {selectedSemesterName}
            </p>
          </div>

          <div className="overflow-x-auto p-6 print:p-0">
            {slots.length === 0 ? (
              <div className="text-center py-16">
                <div className="text-4xl mb-4">📭</div>
                <h3 className="text-xl font-bold text-slate-900 mb-2">No Timetable Found</h3>
                <p className="text-slate-500 max-w-md mx-auto">
                  There is no generated timetable for this semester yet. Go back to Design TT to generate one.
                </p>
                <Button className="mt-6 bg-blue-600 hover:bg-blue-700 text-white" onClick={() => router.push('/design-tt')}>Go to Design TT</Button>
              </div>
            ) : (
              <table className="w-full border-collapse min-w-[1200px] print:min-w-full print:text-sm">
                <thead>
                  <tr>
                    <th className="border border-slate-200 bg-slate-100 p-4 print:p-2 text-center font-bold text-slate-700 w-32 print:w-24">Day / Time</th>
                    {periods.map((p: any) => (
                      <th key={p.id} className="border border-slate-200 bg-slate-100 p-3 print:p-1.5 text-center w-40 print:w-auto">
                        <div className="font-bold text-slate-800">{p.type === 'Class' ? `Period ${p.period_number}` : p.type}</div>
                        <div className="text-xs text-slate-500 font-semibold mt-1">{p.start_time.substring(0, 5)} - {p.end_time.substring(0, 5)}</div>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {days.map((day: any) => (
                    <tr key={day.id}>
                      <td className="border border-slate-200 bg-slate-50 p-4 print:p-2 text-center font-bold text-slate-800">
                        {day.name}
                      </td>
                      {periods.map((period: any) => {
                        if (period.type === 'Break' || period.type === 'Lunch') {
                          return (
                            <td key={period.id} className="border border-slate-200 bg-slate-50/50 p-2 print:p-1 text-center align-middle relative overflow-hidden">
                               <div className="absolute inset-0 bg-[repeating-linear-gradient(45deg,transparent,transparent_10px,rgba(0,0,0,0.02)_10px,rgba(0,0,0,0.02)_20px)]" />
                               <span className="relative z-10 text-slate-400 font-bold tracking-widest uppercase text-xs rotate-[-90deg] inline-block mt-4 print:mt-1">{period.type}</span>
                            </td>
                          )
                        }

                        const slot = grid[day.day_of_week]?.[period.period_number]
                        
                        if (!slot) {
                          return (
                            <td key={period.id} className="border border-slate-200 p-2 print:p-1 text-center bg-white">
                              <span className="text-slate-300 font-medium text-xl">-</span>
                            </td>
                          )
                        }

                        const isLab = slot.subjects?.type === 'Lab'
                        
                        return (
                          <td key={period.id} className={`border border-slate-200 p-3 print:p-1.5 text-center align-middle ${isLab ? 'bg-cyan-50/70 border-cyan-100' : 'bg-blue-50/50 border-blue-100'}`}>
                            <div className="flex flex-col gap-1 print:gap-0.5 items-center justify-center">
                              <span className="text-sm print:text-xs font-bold text-slate-900 leading-tight line-clamp-3" title={slot.subjects?.name}>
                                {slot.subjects?.name}
                              </span>
                            </div>
                          </td>
                        )
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
